# image:
#   name: hashicorp/terraform:light

stages:
  - build
  - test
  - deploy

build-job:
  image: gradle:8.7-jdk17-alpine
  stage: build
  script:
    - ./gradlew clean bootJar
  artifacts:
    paths:
      - "build/libs/*.jar"

test-job:
  stage: test
  script:
    - echo "testing"
  dependencies:
    - build-job

deploy-job:
  image: docker:latest
  stage: deploy
  services:
        - name: docker:dind
  script:
    - echo  "Deploy"
    - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  dependencies:
    - build-job
  when: on_success
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "prod"

