# image:
#   name: hashicorp/terraform:light

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Starting build"

test-job:
  stage: test
  script:
    - echo "testing"

deploy-job:
  stage: deploy
  script:
    - echo  "Deploy"
