stages:
  - gen_keys
  - tf_plan
  - tf_apply
  - ans_config
  - tf_destroy

variables:
  ENVIRONMENT: "prod"
  TF_ADDRESS: https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/terraform/state/votingly-tf

gen_keys:
  image: bash:latest
  stage: gen_keys
  script:
    - apk update && apk add openssh-client
    - mkdir deploy/.creds && cd deploy/.creds
    - base64 -d $SA_GCP > gcloud_sa_compute_admin.json && echo "Service account successfully decoded"
    - ssh-keygen -f vm_key -q -t rsa -N "" && echo "Keys successfully generated"
  artifacts:
    name: keys
    expire_in: "1 day"
    paths:
      - deploy/.creds

.provision:
  script:
    - >
        terraform init
        -backend-config="address=${TF_ADDRESS}"
        -backend-config="lock_address=${TF_ADDRESS}/lock"
        -backend-config="unlock_address=${TF_ADDRESS}/lock"
        -backend-config="username=gitlab-ci-token"
        -backend-config="password=${CI_JOB_TOKEN}"
        -backend-config="lock_method=POST"
        -backend-config="unlock_method=DELETE"
        -backend-config="retry_wait_min=5"

dry_provision:
  image:
    name: hashicorp/terraform:light
  stage: tf_plan
  extends: .provision
  script:
    - terraform validate
    - terraform plan
