# image:
#   name: hashicorp/terraform:light

stages:
  - build
  - test
  - deploy

# build-job:
#   before_install:
#     # login to registry
#     - docker login registry.gitlab.com
#   stage: build
#   script:
#     - echo "Starting build"
#     - ./gradlew bootBuildImage
#     - docker push registry.gitlab.com/kdg-ti/integration-4/2023-2024/team-9/int4t9

gradle-build:
  image: gradle:8.7-jdk17-alpine
  stage: build
  script:
    - ./gradlew clean bootJar
  artifacts:
    paths:
      - "build/libs/*.jar"

test-job:
  stage: test
  script:
    - echo "testing"
  dependencies:
    - gradle-build

deploy-job:
  image: docker:latest
  stage: deploy
  services:
        - name: docker:dind
  script:
    - echo  "Deploy"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  dependencies:
    - test-job
  only:
    - prod
