version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Student1234
      - POSTGRES_DB=int4t9

volumes:
  pgdata:
