version: '3.8'

services:
  int4t9-db:
    container_name: int4t9-db
    image: postgres:16.1-alpine
    restart: unless-stopped
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Student1234
      - POSTGRES_DB=int4t9

  int4t9-test-db:
    container_name: int4t9-test-db
    image: postgres:16.1-alpine
    restart: unless-stopped
    ports:
      - 5331:5432
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Student1234
      - POSTGRES_DB=int4t9

volumes:
  pgdata:
  pgdata_test: