#
# server.port=8081

# DB
# spring.datasource.url=jdbc:postgresql://int4t9-db:5432/int4t9
# spring.datasource.platform=postgres
# spring.datasource.username=postgres
# spring.datasource.password=Student1234
# spring.datasource.driver-class-name=org.h2.Driver
# spring.sql.init.data-locations=classpath:/sql/data.sql

spring:
  devtools:
    restart:
      enabled: 'true'
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
      - src/main/
    livereload:
      enabled: 'true'
  thymeleaf:
    cache: 'false'
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/, classpath:/static/
      cache:
        period: 0
  sql:
    init:
      data-locations: 'classpath:/sql/data.sql'
  datasource:
    password: 'Student1234'
    username: 'postgres'
    url: 'jdbc:postgresql://int4t9-db:5432/int4t9'

logging:
  level:
    root: WARN
    be:
      kdg:
        team9: 
          integration4: DEBUG
