stages:
  - generate-secrets

# REQUIRED - for child pipeline
workflow:
  rules:
    - when: always

# cache:
#   key: "${TF_ROOT}"
#   paths:
#     - ${TF_ROOT}/.terraform/
#     - deploy/.creds/

generate-secrets:
  image: bash:latest
  stage: generate-secrets
  script:
    - apk update && apk add openssh-client
    - mkdir deploy/.creds 
    - cd deploy/.creds
    - echo $SA_GCP | base64 -d > gcloud_sa_compute_admin.json && echo "Service account successfully decoded"
    - ssh-keygen -f vm_key -q -t rsa -N "" && echo "Keys successfully generated"
    - pwd
    - ls deploy/.creds
