# TODO - Self host terraform images becuase of terraform not open source anymore 
image:
  name: "hashicorp/terraform:latest"
  # name: "registry.gitlab.com/gitlab-org/terraform-images/branches/v1-8-0-1.5:f61b9582b11027bd80fb52ce44d266dc1d75e2dd"

stages:
  - generate-secrets
  - validate
  - build
  - deploy
  - ansible
  - cleanup

# REQUIRED - for child pipeline
workflow:
  rules:
    - when: always

variables:
  # ENVIRONMENT: "prod"
  # TF_ADDRESS: https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/terraform/state/votingly-tf
  TF_ROOT: ${CI_PROJECT_DIR}/deploy/prod  # The relative path to the root directory of the Terraform project
  TF_STATE_NAME: default      # The name of the state file used by the GitLab Managed Terraform state backend

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - deploy/.creds/

generate-secrets:
  image: bash:latest
  stage: generate-secrets
  script:
    # - apk update && apk add openssh-client
    - mkdir deploy/.creds && cd deploy/.creds
    - echo $SA_GCP | base64 -d > gcloud_sa_compute_admin.json && echo "Service account successfully decoded"
    # - ssh-keygen -f vm_key -q -t rsa -N "" && echo "Keys successfully generated"
  # artifacts:
  #   name: keys
  #   # public: false
  #   expire_in: "1 hour"
  #   paths:
  #     - deploy/.creds

terraform:fmt:
  stage: validate
  script:
    - gitlab-terraform fmt
  allow_failure: true

terraform:validate:
  stage: validate
  script:
    - gitlab-terraform validate

terraform:build:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  resource_group: ${TF_STATE_NAME}
  artifacts:
    # The next line, which disables public access to pipeline artifacts, may not be available everywhere.
    # See: https://docs.gitlab.com/ee/ci/yaml/#artifactspublic
    # public: false
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

terraform:deploy:
  stage: deploy
  script:
    - gitlab-terraform apply
  resource_group: ${TF_STATE_NAME}
  # when: manual
  # artifacts:
  #   name: vm_ip
  #   expire_in: "1 hour"
  #   paths:
  #     - '../.creds/vm_ip'

# ansible:
#   # image: python:3.9.17-slim-bullseye
#   image: alpine/ansible:latest
#   stage: ansible
#   # allow_failure: true
#   script:
#     - chmod 750 ansible_files
#     - cd deploy/ansible
#     - ansible --version
#     - ansible-playbook install_nginx.yml

terraform:drydestroy:
  stage: cleanup
  script:
    - gitlab-terraform plan -destroy
  resource_group: ${TF_STATE_NAME}
  when: manual

terraform:destroy:
  stage: cleanup
  script:
    - gitlab-terraform destroy
  resource_group: ${TF_STATE_NAME}
  when: manual
