image:
  name: ${TF_CONTAINER_IMAGE}

stages:
  - generate-secrets
  - validate
  - plan
  - deploy

# REQUIRED - for child pipeline
workflow:
  rules:
    - when: always

cache:
  # key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - ${CI_PROJECT_DIR}/deploy/.creds/

generate-secrets:
  stage: generate-secrets
  trigger:
    include: ${CI_PROJECT_DIR}/deploy/.gitlab-ci-generate-secrets.yml
    strategy: depend

terraform:fmt:
  stage: validate
  script:
    - gitlab-terraform fmt -var project_root=${CI_PROJECT_DIR}
  allow_failure: true

terraform:validate:
  stage: validate
  script:
    - pwd
    - ls ${CI_PROJECT_DIR}/deploy/.creds
    - gitlab-terraform validate -var project_root=${CI_PROJECT_DIR}

terraform:plan:
  stage: plan
  script:
    - gitlab-terraform plan -var project_root=${CI_PROJECT_DIR}
    - gitlab-terraform plan-json -var project_root=${CI_PROJECT_DIR}
  resource_group: ${TF_STATE_NAME}
  artifacts:
    # The next line, which disables public access to pipeline artifacts, may not be available everywhere.
    # See: https://docs.gitlab.com/ee/ci/yaml/#artifactspublic
    # public: false
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

terraform:deploy:
  stage: deploy
  script:
    - gitlab-terraform apply -var project_root=${CI_PROJECT_DIR}
  resource_group: ${TF_STATE_NAME}
  # when: manual
  # artifacts:
  #   name: vm_ip
  #   expire_in: "1 hour"
  #   paths:
  #     - '../.creds/vm_ip'

# ansible:
#   # image: python:3.9.17-slim-bullseye
#   image: alpine/ansible:latest
#   stage: ansible
#   # allow_failure: true
#   script:
#     - chmod 750 ansible_files
#     - cd deploy/ansible
#     - ansible --version
#     - ansible-playbook install_nginx.yml
