image:
  name: ${TF_CONTAINER_IMAGE}

stages:
  - generate-secrets
  - preview
  - cleanup

# REQUIRED - for child pipeline
workflow:
  rules:
    - when: always

cache:
  # key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - ${CI_PROJECT_DIR}/deploy/.creds/

generate-secrets:
  stage: generate-secrets
  trigger:
    include: ${CI_PROJECT_DIR}/deploy/.gitlab-ci-generate-secrets.yml
    strategy: depend

# terraform:drydestroy:
#   stage: preview
#   script:
#     - gitlab-terraform plan -destroy -var project_root=${CI_PROJECT_DIR}
#   resource_group: ${TF_STATE_NAME}
  # when: manual

terraform:destroy:
  stage: cleanup
  script:
    - ls ${CI_PROJECT_DIR}/deploy/.creds
    - gitlab-terraform destroy -var project_root=${CI_PROJECT_DIR}
  resource_group: ${TF_STATE_NAME}
  # when: manual
