image:
  name: ${TF_CONTAINER_IMAGE}

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/deploy/prod  # The relative path to the root directory of the Terraform project

stages:
  - generate-secrets
  - preview
  - cleanup

workflow:
  rules:
    - when: always

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - deploy/.creds/

generate-secrets:
  image: bash:latest
  stage: generate-secrets
  script:
    - mkdir deploy/.creds && cd deploy/.creds
    - echo $SA_GCP | base64 -d > gcloud_sa_compute_admin.json && echo "Service account successfully decoded"

# terraform:drydestroy:
#   stage: preview
#   script:
#     - gitlab-terraform plan -destroy
#   resource_group: ${TF_STATE_NAME}
  # when: manual

terraform:destroy:
  stage: cleanup
  script:
    - gitlab-terraform destroy
  resource_group: ${TF_STATE_NAME}
  # when: manual
