image:
  name: ${TF_CONTAINER_IMAGE}

stages:
  - generate-secrets
  - preview
  - cleanup

# REQUIRED - for child pipeline
workflow:
  rules:
    - when: always

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - deploy/.creds/

generate-secrets:
  stage: generate-secrets
  trigger:
    include: .gitlab-ci-generate-secrets.yml
    strategy: depend

# terraform:drydestroy:
#   stage: preview
#   script:
#     - gitlab-terraform plan -destroy
#   resource_group: ${TF_STATE_NAME}
  # when: manual

terraform:destroy:
  stage: cleanup
  script:
    - gitlab-terraform destroy
  resource_group: ${TF_STATE_NAME}
  # when: manual
