stages:
  - generate-secrets

# REQUIRED - for child pipeline
workflow:
  rules:
    - when: always

cache:
  # key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - ${CI_PROJECT_DIR}/deploy/.creds

generate-secrets:
  image: bash:latest
  stage: generate-secrets
  script:
    - apk update && apk add openssh-client
    - mkdir -p ${CI_PROJECT_DIR}/deploy/.creds
    - cd ${CI_PROJECT_DIR}/deploy/.creds
    - echo $SA_GCP | base64 -d > ${CI_PROJECT_DIR}/deploy/.creds/gcloud_sa_compute_admin.json && echo "Service account successfully decoded"
    # - cat ${CI_PROJECT_DIR}/deploy/.creds/gcloud_sa_compute_admin.json
    - ssh-keygen -f vm_key -q -t rsa -N "" <<<y && echo "Keys successfully generated"
    - pwd
    - ls -al ${CI_PROJECT_DIR}/deploy/.creds
