image:
  name: ${TF_CONTAINER_IMAGE}

stages:
  - generate-secrets
  - validate
  - plan
  - deploy
  - setup

# REQUIRED - for child pipeline
workflow:
  rules:
    - when: always

cache:
  # key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/
    - ${CI_PROJECT_DIR}/deploy/.creds/

generate-secrets:
  stage: generate-secrets
  trigger:
    include: ${CI_PROJECT_DIR}/deploy/.gitlab-ci-generate-secrets.yml
    strategy: depend

terraform:fmt:
  stage: validate
  script:
    - gitlab-terraform fmt
  allow_failure: true

terraform:validate:
  stage: validate
  script:
    - pwd
    - ls ${CI_PROJECT_DIR}/deploy/.creds
    - gitlab-terraform validate

terraform:plan:
  stage: plan
  script:
    - gitlab-terraform plan -var project_root=${CI_PROJECT_DIR}
    - gitlab-terraform plan-json -var project_root=${CI_PROJECT_DIR}
  resource_group: ${TF_STATE_NAME}
  artifacts:
    # The next line, which disables public access to pipeline artifacts, may not be available everywhere.
    # See: https://docs.gitlab.com/ee/ci/yaml/#artifactspublic
    # public: false
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

terraform:deploy:
  stage: deploy
  script:
    - gitlab-terraform apply
  resource_group: ${TF_STATE_NAME}
  # when: manual

vm:installation:
  image: google/cloud-sdk:latest
  stage: setup
  script:
    - gcloud auth login --cred-file=${CI_PROJECT_DIR}/deploy/.creds/gcloud_sa_compute_admin.json
    - gcloud compute scp ${CI_PROJECT_DIR}/deploy/vm_res/installation.sh votingly-testing-vm:/tmp
    - gcloud compute ssh --zone "europe-west1-b" "votingly-testing-vm" --project "int4t9" -- 'bash /tmp/installation.sh'
  # when: manual
