version: '3.2'
services:
    https-portal:
        image:  steveltn/https-portal:1
        ports:
            - "80:80"
            - "443:443"
        restart: always
        environment:
            # DOMAINS:  "votingly.tech -> http://my-apache-app:80"
            DOMAINS:  "votingly.tech -> http://votingly-app:80"
            STAGE:  "production"
#             FORCE_RENEW:  "false"
        networks:
            - bridged
        depends_on:
            - "my-apache-app"
        volumes:
            - https-portal-data:/var/lib/https-portal
            - /tmp/https-portal/log:/var/log/nginx/
            - /tmp/https-portal/logrotate:/var/lib/logrotate/
    
    # my-apache-app:
    #     image: httpd:2.4
    #     networks:
    #         - bridged

    votingly-app:
        image: registry.gitlab.com/kdg-ti/integration-4/2023-2024/team-9/int4t9:latest
        networks:
            - bridged
    
volumes:
    https-portal-data:

networks:
    bridged:
