version: '3.2'
services:
    https-portal:
        image:  steveltn/https-portal:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        environment:
            DOMAINS:  "votingly.tech -> http://web-app:80"
            # STAGE:  "production"
            STAGE: local
#             FORCE_RENEW:  "false"
        networks:
            - bridged
        depends_on:
            - "web-app"
        volumes:
            - https-portal-data:/var/lib/https-portal
            - /home/admin/https-portal/log:/var/log/nginx/
            - /home/admin/https-portal/logrotate:/var/lib/logrotate/

    # web-app:
    #     image: httpd:2.4
    #     networks:
    #         - bridged

    web-app:
        image: registry.gitlab.com/kdg-ti/integration-4/2023-2024/team-9/int4t9:latest
        pull_policy: always
        networks:
            - bridged

volumes:
    https-portal-data:

networks:
    bridged:
